package com.octogonapus.omj.agent.interpreter

internal sealed class OperandStackOperation {
    object NOP : OperandStackOperation()
    data class PushConstInt(val value: Int) : OperandStackOperation()
    data class PushConstLong(val value: Long) : OperandStackOperation()
    data class PushConstFloat(val value: Float) : OperandStackOperation()
    data class PushConstDouble(val value: Double) : OperandStackOperation()
    data class PushConstByte(val value: Int) : OperandStackOperation()
    data class PushConstShort(val value: Int) : OperandStackOperation()
    data class NewArray(val type: Int) : OperandStackOperation()
    object PushNullRef : OperandStackOperation()
    object LoadIntFromArray : OperandStackOperation()
    object StoreIntoIntArray : OperandStackOperation()
    object LoadLongFromArray : OperandStackOperation()
    object StoreIntoLongArray : OperandStackOperation()
    object LoadFloatFromArray : OperandStackOperation()
    object StoreIntoFloatArray : OperandStackOperation()
    object LoadDoubleFromArray : OperandStackOperation()
    object StoreIntoDoubleArray : OperandStackOperation()
    object LoadRefFromArray : OperandStackOperation()
    object StoreIntoRefArray : OperandStackOperation()
    object LoadByteFromArray : OperandStackOperation()
    object StoreIntoByteArray : OperandStackOperation()
    object LoadCharFromArray : OperandStackOperation()
    object StoreIntoCharArray : OperandStackOperation()
    object LoadShortFromArray : OperandStackOperation()
    object StoreIntoShortArray : OperandStackOperation()
    object Pop : OperandStackOperation()
    object Pop2 : OperandStackOperation()
    object Dup : OperandStackOperation()
    object DupX1 : OperandStackOperation()
    object DupX2 : OperandStackOperation()
    object Dup2 : OperandStackOperation()
    object Dup2X1 : OperandStackOperation()
    object Dup2X2 : OperandStackOperation()
}
